version: 2

jobs:
  build:
    docker:
      - image: hoangitdct/touchbuild:latest # primary image
        environment:
          DATABASE_HOST: localhost

      - image: postgres:9.6.3
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: touchdb_test

    working_directory: touch_app

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - setup_remote_docker:
          reusable: true

      - restore_cache:
          key: dependency-cache-{{ checksum "backend/src/package.json" }}

      - run:
          name: Install node modules
          command: |
            adduser --quiet --disabled-password --gecos ""  foo
            chown -R foo /home/foo
            chown -R foo /usr/local
            chown -R foo /touch_app
            cp backend/src/package.json backend/
            runuser -l  foo -c 'cd /touch_app/backend && npm install'

      - save_cache:
          key: dependency-cache-{{ checksum "backend/src/package.json" }}
          paths:
            - .backend/node_modules

      - run:
          name: Testing backend
          command: |
            cd backend/src
            chmod +x ./wait_for_it.sh
            ./wait_for_it.sh localhost:5432 -- npm run test

      - deploy:
          name: Build and push Docker image
          command: |
            cd rancher
            chmod +x build.sh
            ./build.sh

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
