version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      # - image: circleci/cci-demo-docker-primary:0.0.2
      - image: hoangitdct/docker-compose:17.03.x-ce # primary image
        
      - image: postgres:9.6.3
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: touchdb_test
      - image: hoangitdct/touchtest

    working_directory: touch_app

    environment:
      TEST_RESULTS: /tmp/test-results

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Start container and verify it's working
          command: |
            set -x
            ls -l
            cd /touch_app/deveops/dockers/backend
            chmod +x ./runner.sh
            ./runner.sh test up
            docker-compose up -d

      - deploy:
          name: Build and push Docker image
          command: |
            echo "deployment"

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results