version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: hoangitdct/touchtest:latest

      - image: postgres:9.6.3
        environment:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: touchdb_test

    working_directory: .

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build service
          command: ls

      - deploy:
          name: Build and push Docker image
          command: |
            echo "################# build"
            # TAG="0.1.${CIRCLE_BUILD_NUM}"
            # docker build -t circleci/cci-demo-docker:$TAG .
            # docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            # docker push circleci/cci-demo-docker:$TAG