# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Hoang Nguyen

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf
COPY dist /touchdb_frontend
