###########################################
# Dockerfile
###########################################

FROM node:slim

MAINTAINER Hoang Nguyen <hoang.nguyencong@asnet.com.vn>

# RUN npm i -g yarn

RUN mkdir /web

RUN adduser foo
RUN chown -R foo /home/foo
RUN chown -R foo /usr/local
RUN chown -R foo /web

# Caching node_modules
COPY package.json /web

# Caching scripts
COPY wait_for_it.sh /usr/local/bin/wait_for_it.sh

# Grant exec permission
RUN su -c "chmod +x /usr/local/bin/wait_for_it.sh"

# Install node_modules

USER foo

RUN npm install --global yarn
RUN cd /web && yarn

USER root

# Copy source code
COPY . /web/src

# Working directory
WORKDIR /web/src
